@extends('layouts.app')

@section('title', 'Login')

@push('styles')
<style>
    body {
        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .login-wrapper {
        width: 100%;
        max-width: 400px;
        padding: 15px;
    }
    .login-card {
        background: rgba(255, 255, 255, 0.95);
        backdrop-filter: blur(10px);
        border: 1px solid rgba(255,255,255,0.2);
        box-shadow: 0 15px 35px rgba(0,0,0,0.1);
        border-radius: 16px;
        padding: 40px 30px;
    }
</style>
@endpush

@section('content')
<div class="login-wrapper">
    <div class="login-card">
        <div class="text-center mb-4">
            <h2 class="fw-bold text-primary"><i class="bi bi-rocket-takeoff"></i> Boily</h2>
            <p class="text-muted">Sign in to your account</p>
        </div>

        <div id="errorAlert" class="alert alert-danger d-none"></div>

        <form id="loginForm">
            <div class="mb-3">
                <label class="form-label">Email address</label>
                <div class="input-group">
                    <span class="input-group-text bg-white"><i class="bi bi-envelope"></i></span>
                    <input type="email" class="form-control" id="email" value="admin@example.com" required>
                </div>
            </div>
            
            <div class="mb-4">
                <label class="form-label">Password</label>
                <div class="input-group">
                    <span class="input-group-text bg-white"><i class="bi bi-lock"></i></span>
                    <input type="password" class="form-control" id="password" value="admin123" required>
                </div>
            </div>

            <button type="submit" class="btn btn-primary w-100 py-2 fw-semibold" id="loginBtn">
                Sign In <i class="bi bi-arrow-right ms-1"></i>
            </button>
        </form>
    </div>
</div>
@endsection

@push('scripts')
<script>
    document.getElementById('loginForm').addEventListener('submit', async (e) => {
        e.preventDefault();
        
        const btn = document.getElementById('loginBtn');
        const alertBox = document.getElementById('errorAlert');
        const email = document.getElementById('email').value;
        const password = document.getElementById('password').value;

        btn.disabled = true;
        btn.innerHTML = '<span class="spinner-border spinner-border-sm"></span> Signing in...';
        alertBox.classList.add('d-none');

        try {
            const res = await api.post('/auth/login', { email, password });
            if(res && res.data && res.data.token) {
                // Save token generated by Sanctum
                api.setToken(res.data.token);
                window.location.href = '/dashboard';
            }
        } catch (error) {
            alertBox.textContent = error.message;
            alertBox.classList.remove('d-none');
            btn.disabled = false;
            btn.innerHTML = 'Sign In <i class="bi bi-arrow-right ms-1"></i>';
        }
    });
</script>
@endpush
